Feature Addition: Contributors Page
dscmbcet/website-3.0 pull request #6
Opened 2024-04-18 18:50 UTC by navaneethvenu

- Add Contributors Page (A page displaying all the Contributors of the Community Project and their Contributions)

Todo:
  - Update Contributor, Contribution dummy data with real data
  - Update Theming
  - Use Better Hero Image (Display Dev Panel too)

2024-04-19 17:16 UTC, xditya approved these changes
LGTM

2024-04-19 21:21 UTC, aurora-0025 requested changes

2024-04-19 21:21 UTC, aurora-0025 commented on src/app/about/mode-toggle.tsx
@navaneethvenu 
This file is located in the 'about' folder. Considering its potential use in multiple pages, particularly within the navbar across various pages, it might be great to place it within the 'components' folder.

2024-04-20 17:14 UTC, RiyaMathew-11 commented on src/app/contributors/components/figma-card.tsx
> +import BenGeorgeNetto from "@/../public/assets/images/team-photos/bengeorgenetto.png";
Let's use a good variable name instead of BenGeorgeNetto? - keep it standardised - like ProfileImage

2024-04-20 17:14 UTC, RiyaMathew-11 commented on src/app/contributors/page.tsx
> +import CloudBottomImage from "@/../public/assets/images/CloudsBottom.png";
So usually when we name asset files - we keep the names in smallcase to avoid confusions in consistency. 

If we are enabling first-letter caps for file names, let's note to maintain this style for all asset files to make them consistent.

2024-04-20 17:14 UTC, RiyaMathew-11 commented on src/app/about/page.tsx
I feel - since this file is like a reference for font styles - keep this separate - maybe in a directory called app/sample/page.tsx - if this needs to be kept as a test page. 

As about page also comes here, this page would go when about page is pushed. Or if this isnt needed, we can remove this.

2024-04-20 18:34 UTC, navaneethvenu commented on src/app/about/mode-toggle.tsx
I've moved everything to a sample folder as @RiyaMathew-11 suggested, the toggle is very different from what we'll be having, and hence this wont be reused. This toggle is only for reference, and will be deleted once the actual toggle arrives.

2024-04-20 18:35 UTC, navaneethvenu commented on src/app/contributors/page.tsx
> +import CloudBottomImage from "@/../public/assets/images/CloudsBottom.png";
fixed (kept names in kebab-case)

2024-04-20 18:35 UTC, navaneethvenu commented on src/app/about/page.tsx
Done, moved to app/sample

2024-04-20 19:07 UTC, RiyaMathew-11 approved these changes

2024-04-20 19:07 UTC, RiyaMathew-11 approved these changes

2024-04-20 19:08 UTC, RiyaMathew-11 approved these changes

2024-04-20 19:09 UTC, RiyaMathew-11 approved these changes

2024-04-21 05:20 UTC, aurora-0025 approved these changes

2024-04-21 09:35 UTC, merged